dist: bionic
os: linux
language: python
python: '3.7'
stages:
  - lint
  - test
env:
  global:
    - TEST_PREPARE_PATH: ~/test_basicswap-prepare
    - TEST_DIR=~/test_basicswap2
    - TEST_RELOAD_PATH=~/test_basicswap1
    - BIN_DIRS=~/cached_bin
    - PARTICL_BINDIR=${BIN_DIRS}/particl
    - BITCOIN_BINDIR=${BIN_DIRS}/bitcoin
    - LITECOIN_BINDIR=${BIN_DIRS}/litecoin
    - XMR_BINDIR=${BIN_DIRS}/monero
cache:
  directories:
    - "$BIN_DIRS"
before_install:
  - sudo apt-get install -y wget python3-pip gnupg unzip protobuf-compiler automake libtool pkg-config
install:
  - travis_retry pip install tox
before_script:
  - wget -O coincurve-anonswap.zip https://github.com/tecnovert/coincurve/archive/anonswap.zip
  - unzip coincurve-anonswap.zip
  - cd coincurve-anonswap
  - python3 setup.py install --force
script:
  - cd $TRAVIS_BUILD_DIR
  - basicswap-prepare --bindir=${BIN_DIRS} --preparebinonly --withcoins=particl,bitcoin,litecoin,monero
  - export DATADIRS="${TEST_DIR}"
  - mkdir -p "${DATADIRS}/bin"
  - cp -r ${BIN_DIR} "${DATADIRS}/bin"
  - mkdir -p "${TEST_RELOAD_PATH}/bin"
  - cp -r ${BIN_DIR} "${TEST_RELOAD_PATH}/bin"
  - mkdir -p "${TEST_PREPARE_PATH}/bin"
  - cp -r ${BIN_DIR} "${TEST_PREPARE_PATH}/bin"
  - tox
after_success:
  - echo "End test"
jobs:
  include:
    - stage: lint
      env:
      cache: false
      install:
        - travis_retry pip install flake8==3.7.0
        - travis_retry pip install codespell==1.15.0
      before_script:
      script:
        - PYTHONWARNINGS="ignore" flake8 --ignore=E501,F841,W503 --exclude=basicswap/contrib,messages_pb2.py,.eggs,.tox
        - codespell --check-filenames --disable-colors --quiet-level=7 --ignore-words=tests/lint/spelling.ignore-words.txt -S .git,.eggs,.tox,gitianpubkeys,*.pyc,*basicswap/contrib,*mnemonics.py
      after_success:
        - echo "End lint"
    - stage: test
      env:
