dist: bionic
os: linux
language: python
python: '3.7'
stages:
  - lint
env:
global:
  - TEST_DIR=~/test_basicswap2/
  - PARTICL_BINDIR=/opt/binaries/particl-0.18.1.2/bin/
  - BITCOIN_BINDIR=/opt/binaries/bitcoin-0.18.0/bin/
  - LITECOIN_BINDIR=/opt/binaries/litecoin-0.17.1/bin/
before_install:
  - sudo apt-get install -y wget gnupg2
before_script:
  - if [ ! -d "/opt/binaries" ]; then mkdir -p "/opt/binaries" ; fi
  - if [ ! -d "$BITCOIN_BINDIR" ]; then cd "/opt/binaries" && wget https://bitcoincore.org/bin/bitcoin-core-0.18.0/bitcoin-0.18.0-x86_64-linux-gnu.tar.gz && tar xvf bitcoin-0.18.0-x86_64-linux-gnu.tar.gz ; fi
  - if [ ! -d "$LITECOIN_BINDIR" ]; then cd "/opt/binaries" && wget https://download.litecoin.org/litecoin-0.17.1/linux/litecoin-0.17.1-x86_64-linux-gnu.tar.gz && tar xvf litecoin-0.17.1-x86_64-linux-gnu.tar.gz ; fi
  - if [ ! -d "$PARTICL_BINDIR" ]; then cd "/opt/binaries" && wget https://github.com/particl/particl-core/releases/download/v0.18.1.2/particl-0.18.1.2-x86_64-linux-gnu_nousb.tar.gz && tar xvf particl-0.18.1.2-x86_64-linux-gnu_nousb.tar.gz ; fi
script:
  - cd $TRAVIS_BUILD_DIR
  - export PARTICL_BINDIR=/opt/binaries/particl-0.18.1.2/bin/
  - export BITCOIN_BINDIR=/opt/binaries/bitcoin-0.18.0/bin/
  - export LITECOIN_BINDIR=/opt/binaries/litecoin-0.17.1/bin/
  - export DATADIRS=~/test_basicswap2/
  - mkdir -p ${DATADIRS}/bin/{particl,bitcoin}
  - cp /opt/binaries/bitcoin-0.18.0-x86_64-linux-gnu.tar.gz ${DATADIRS}/bin/bitcoin
  - python setup.py test
after_success:
  - echo "End test"
jobs:
  include:
    - stage: lint
      env:
      cache: false
      language: python
      python: '3.7'
      install:
        - travis_retry pip install flake8==3.5.0
        - travis_retry pip install codespell==1.15.0
      before_script:
      script:
        - PYTHONWARNINGS="ignore" flake8 --ignore=E501,F841 --exclude=key.py,messages_pb2.py,.eggs
        - codespell --check-filenames --disable-colors --quiet-level=7 -S .git,.eggs,gitianpubkeys
      after_success:
        - echo "End lint"
