version: '3'
services:

    swapclient:
        stop_grace_period: 5m
        build:
            context: ../
            args:
                - WITH_COINS=--withcoins=monero
                - WITHOUT_COINS=--withoutcoins=litecoin
        volumes:
            - ${COINDATA_PATH}:/coindata
        ports:
            - "${HTML_PORT}"  # Expose only to localhost, see .env

volumes:
  coindata:
    driver: local

