version: '3'
services:

    swapclient:
        build:
            context: ../
        volumes:
            - ./coindata:/coindata
        ports:
            - "${HTML_PORT}"  # Expose only to localhost, see .env

volumes:
  coindata:
    driver: local

