version: '3.3'

services:
    particl_core:
        image: i_particl
        build:
            context: particl
            dockerfile: Dockerfile
        container_name: particl_core
        volumes:
            - ${DATA_PATH}/particl:/data
        #ports:
        #    - "51738:51738"
        expose:
            - 51735
        logging:
            driver: "json-file"
            options:
                max-size: "10m"
                max-file: "3"
        restart: unless-stopped
    #bitcoin_core:
        #image: i_bitcoin
        #build:
            #context: bitcoin
            #dockerfile: Dockerfile
        #container_name: bitcoin_core
        #volumes:
            #- ${DATA_PATH}/bitcoin:/data
        ##ports:
        ##    - "8333:8333"
        #expose:
            #- 8332
        #logging:
            #driver: "json-file"
            #options:
                #max-size: "10m"
                #max-file: "3"
        #restart: unless-stopped
    litecoin_core:
        image: i_litecoin
        build:
            context: litecoin
            dockerfile: Dockerfile
        container_name: litecoin_core
        volumes:
            - ${DATA_PATH}/litecoin:/data
        logging:
            driver: "json-file"
            options:
                max-size: "10m"
                max-file: "3"
        restart: unless-stopped
    #monero_daemon:
        #image: i_monero_daemon
        #build:
            #context: monero_daemon
            #dockerfile: Dockerfile
        #container_name: monero_daemon
        #volumes:
            #- ${DATA_PATH}/monero_daemon:/data
        #ports:
            #- "18080:18080"
        #expose:
            #- 8332
        #logging:
            #driver: "json-file"
            #options:
                #max-size: "10m"
                #max-file: "3"
        #restart: unless-stopped
    #monero_wallet:
        #image: i_monero_wallet
        #build:
            #context: monero_wallet
            #dockerfile: Dockerfile
        #container_name: monero_wallet
        #volumes:
            #- ${DATA_PATH}/monero_wallet:/data
        #expose:
            #- 8332
        #logging:
            #driver: "json-file"
            #options:
                #max-size: "10m"
                #max-file: "3"
        #restart: unless-stopped
    swapclient:
        image: i_swapclient
        build:
            context: swapclient
            dockerfile: Dockerfile
        container_name: swapclient
        volumes:
            - ${DATA_PATH}/swapclient:/data
        ports:
            - "${HTML_PORT}"  # Expose only to localhost, see .env
        environment:
            - TZ
        logging:
            driver: "json-file"
            options:
                max-size: "10m"
                max-file: "5"
        depends_on:
            - particl_core
        restart: unless-stopped
    swapprepare:
        image: i_swapclient
        build:
            context: swapclient
            dockerfile: Dockerfile
        container_name: swapprepare
        volumes:
            - ${DATA_PATH}/swapclient:/data/swapclient
            - ${DATA_PATH}/monero_daemon:/data/monero_daemon
            - ${DATA_PATH}/monero_wallet:/data/monero_wallet
            - ${DATA_PATH}/particl:/data/particl
            - ${DATA_PATH}/bitcoin:/data/bitcoin
            - ${DATA_PATH}/litecoin:/data/litecoin
        environment:
            - TZ
            - PART_RPC_HOST
            - LTC_RPC_HOST
            - BTC_RPC_HOST
            - PART_RPC_PORT
            - LTC_RPC_PORT
            - BTC_RPC_PORT
            - XMR_RPC_HOST
            - BASE_XMR_RPC_PORT
            - BASE_XMR_ZMQ_PORT
            - BASE_XMR_WALLET_PORT
            - XMR_WALLET_RPC_HOST
            - XMR_WALLET_RPC_USER
            - XMR_WALLET_RPC_PWD
            - DEFAULT_XMR_RESTORE_HEIGHT
            - UI_HTML_PORT
            - PART_ZMQ_PORT
            - PART_RPC_USER
            - PART_RPC_PWD
            - BTC_RPC_USER
            - BTC_RPC_PWD
            - LTC_RPC_USER
            - LTC_RPC_PWD
            - PART_DATA_DIR
            - LTC_DATA_DIR
            - BTC_DATA_DIR
            - XMR_DATA_DIR
            - XMR_WALLETS_DIR
            - COINS_BIND_IP
        restart: "no"
networks:
    default:
        external:
            name: coinswap_network
