    swapprepare:
        image: i_swapclient
        build:
            context: swapclient
            dockerfile: Dockerfile
        container_name: swapprepare
        volumes:
            - ${DATA_PATH}/swapclient:/data/swapclient
            - ${DATA_PATH}/monero_daemon:/data/monero_daemon
            - ${DATA_PATH}/monero_wallet:/data/monero_wallet
            - ${DATA_PATH}/particl:/data/particl
            - ${DATA_PATH}/bitcoin:/data/bitcoin
            - ${DATA_PATH}/litecoin:/data/litecoin
        environment:
            - TZ
            - PART_RPC_HOST
            - LTC_RPC_HOST
            - BTC_RPC_HOST
            - PART_RPC_PORT
            - LTC_RPC_PORT
            - BTC_RPC_PORT
            - XMR_RPC_HOST
            - BASE_XMR_RPC_PORT
            - BASE_XMR_ZMQ_PORT
            - BASE_XMR_WALLET_PORT
            - XMR_WALLET_RPC_HOST
            - XMR_WALLET_RPC_USER
            - XMR_WALLET_RPC_PWD
            - DEFAULT_XMR_RESTORE_HEIGHT
            - UI_HTML_PORT
            - PART_ZMQ_PORT
            - PART_RPC_USER
            - PART_RPC_PWD
            - BTC_RPC_USER
            - BTC_RPC_PWD
            - LTC_RPC_USER
            - LTC_RPC_PWD
            - PART_DATA_DIR
            - LTC_DATA_DIR
            - BTC_DATA_DIR
            - XMR_DATA_DIR
            - XMR_WALLETS_DIR
            - COINS_RPCBIND_IP
        restart: "no"
